Feature: ireland support
RateTheLandlord/rtl-frontend pull request #130
Opened 2024-06-21 17:02 UTC by DoxxableSetanta

- Add resources for Ireland support 
- Hiding post code for Ireland
- Readme changes

closes #128

2024-06-21 17:03 UTC, DoxxableSetanta commented
If ok with code - please hold off on merging until we discuss release strategy

2024-06-22 12:34 UTC, kellenwiltshire requested changes
Small change needed, otherwise looks good!

2024-06-22 12:34 UTC, kellenwiltshire commented on components/modal/EditReviewModal.tsx
Small change for this file, we should remove the postal code box for Ireland to be consistent.

![image](https://github.com/RateTheLandlord/rtl-frontend/assets/31140634/8a01f92c-1025-449d-978c-148e9f25ba3b)

2024-06-23 16:26 UTC, DoxxableSetanta commented on components/modal/EditReviewModal.tsx
Cool, thanks! Should have bandwith later in week to address this

2024-06-28 11:41 UTC, kellenwiltshire approved these changes
Looks good! Merging into the develop branch.

2024-06-28 11:43 UTC, merged